# Generated by Django 5.1 on 2024-09-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0010_registerfinanca"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeragenda",
            name="obs_consulta",
            field=models.TextField(default="", max_length=3000),
        ),
        migrations.AlterField(
            model_name="registerfinanca",
            name="despezas",
            field=models.DecimalField(decimal_places=2, default="-", max_digits=10),
        ),
    ]
