# Generated by Django 5.1 on 2024-09-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0012_registeragenda_positivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registermedico",
            name="pagMes",
            field=models.TextField(default="A pagar"),
        ),
    ]
