# Generated by Django 5.1 on 2024-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0013_alter_registermedico_pagmes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registermedico",
            name="pagMes",
            field=models.CharField(default="A pagar", max_length=100),
        ),
    ]
