# Generated by Django 5.1 on 2024-09-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0014_alter_registermedico_pagmes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerpacientes",
            name="pagMes",
            field=models.CharField(default="A pagar", max_length=50),
        ),
    ]
